sensor:
  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Active_Power_L1"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Active Power L1"
    register_type: holding
    address: 30013
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Active_Power_L2"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Active Power L2"
    register_type: holding
    address: 30015
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Active_Power_L3"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Active Power L3"
    register_type: holding
    address: 30017
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Active_Power_Total"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Active Power Total"
    register_type: holding
    address: 30053
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD
