sensor:
  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 10
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Export_Reactive_Energy_Since_Last_Reset"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Export Reactive Energy Since Last Reset"
    register_type: holding
    address: 30079
    unit_of_measurement: "kVarh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    filters:
      - multiply: 1.0
    value_type: U_DWORD