sensor:
  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Frequency"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Frequency"
    register_type: holding
    address: 30071
    unit_of_measurement: "Hz"
    state_class: "measurement"
    accuracy_decimals: 2
    filters:
      - multiply: 1.0
    value_type: U_DWORD