sensor:
  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Phase_Angle_L1"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Phase Angle L1"
    register_type: holding
    address: 30037
    unit_of_measurement: "-"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Phase_Angle_L2"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Phase Angle L2"
    register_type: holding
    address: 30039
    unit_of_measurement: "-"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Phase_Angle_L3"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Phase Angle L3"
    register_type: holding
    address: 30041
    unit_of_measurement: "-"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Phase_Angle_Total"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Phase Angle Total"
    register_type: holding
    address: 30067
    unit_of_measurement: "-"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD