sensor:
  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Reactive_Power_L1"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Reactive Power L1"
    register_type: holding
    address: 30025
    unit_of_measurement: "Var"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Reactive_Power_L2"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Reactive Power L2"
    register_type: holding
    address: 30027
    unit_of_measurement: "Var"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Reactive_Power_L3"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Reactive Power L3"
    register_type: holding
    address: 30029
    unit_of_measurement: "Var"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Reactive_Power_Total"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Reactive Power Total"
    register_type: holding
    address: 30061
    unit_of_measurement: "Var"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD
