sensor:
  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Maximum_Active_Power_Demand"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Maximum Active Power Demand"
    register_type: holding
    address: 30087
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 1.0
    value_type: U_DWORD