sensor:
  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_THD_Current_L1"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - THD Current L1"
    register_type: holding
    address: 30241
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_THD_Current_L2"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - THD Current L2"
    register_type: holding
    address: 30243
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_THD_Current_L3"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - THD Current L3"
    register_type: holding
    address: 30245
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_THD_Current_Average"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - THD Current Average"
    register_type: holding
    address: 30251
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 1.0
    value_type: U_DWORD