sensor:
  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_THD_Voltage_Phase_L1"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - THD Voltage Phase L1"
    register_type: holding
    address: 30235
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_THD_Voltage_Phase_L2"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - THD Voltage Phase L2"
    register_type: holding
    address: 30237
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_THD_Voltage_Phase_L3"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - THD Voltage Phase L3"
    register_type: holding
    address: 30239
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_THD_Voltage_Phase_Average"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - THD Voltage Phase (Average)"
    register_type: holding
    address: 30249
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 1.0
    value_type: U_DWORD
