sensor:
  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Voltage_Phase_L1"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Voltage Phase L1"
    register_type: holding
    address: 30001
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Voltage_Phase_L2"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Voltage Phase L2"
    register_type: holding
    address: 30003
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Voltage_Phase_L3"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Voltage Phase L3"
    register_type: holding
    address: 30005
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: ${slave_modbus_controller_id}
    skip_updates: 2
    id: "${entities_id_prefix}_${slave_entities_prefix_id}_Voltage_Phase_Average"
    name: "${entities_name_prefix} - ${slave_entities_prefix_name} - Voltage Phase (Average)"
    register_type: holding
    address: 30043
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 1.0
    value_type: U_DWORD
