substitutions:
  name: !secret host_name                                           # Name in ESPhome
  device_description: "Esphome component for Eastron SDM630"        # Description in ESPhome

  # To be implemented in all the YAML files
  entities_id_prefix: !secret entities_id_prefix                     # All entities in Home Assistant will start with this text to help identify the entities
  entities_name_prefix: !secret entities_name_prefix                 # All entities in Home Assistant will start with this text to help identify the entities

#external_components:
#  - source: github://pr#5586
#      components: [ ota_http ]

packages:
  api: !include config/api.yaml
  mdns: !include
    file: config/mdns.yaml
    vars:
      mdns_disable: false # Enable auto-discovery in ESPHome Dashboard & Home Assistant
      #mdns_disable: true # Disable auto-discovery in ESPHome Dashboard & Home Assistant
  mqtt: !include
    file: config/mqtt.yaml
    vars:
      mqtt_discovery: false # If "api" is included, turn off autodiscovery feature for Home Assistant
      #mqtt_discovery: true # If "api" is NOT included, turn on MQTT autodiscovery feature for Home Assistant
  wifi: !include config/wifi.yaml

  # Core OTA (client UPLOADS Firmware to ESP32 Device)
  ota: !include config/ota.yaml

  # External component OTA (ESP32 Device DOWNLOADS Firmware from HTTP WebServer)
  #ota_http: !include config/ota_http.yaml

  restart: !include config/restart.yaml

  #web_server: !include config/web_server.yaml

  # Select the Board you plan to use
  #core: !include boards/esp32-s3-wroom-1-n16r8.yaml
  core: !include boards/esp32-s3_m5stack_atoms3.yaml

  logger: !include config/logging.yaml
  captive_portal: !include config/captive_portal.yaml
  modbus_init: !include config/modbus_init.yaml