wifi:
  power_save_mode: none # Disabling Power Saving Could help reduce issues with OTA
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  ap:
    ssid: !secret wifi_ap_ssid
    password: !secret wifi_ap_password
